from application import db, Category, User, Item

#db.create_all()
user = User(id="hany",name="Hany")
db.session.add(user)

soccer = Category(name="Soccer", user=user)
basketball = Category(name="Basketball", user=user)
baseball = Category(name="Baseball", user=user)
frisbee = Category(name="Frisbee", user=user)
snowboarding = Category(name="Snowboarding", user=user)
rock = Category(name="Rock Climbing", user=user)
foosball = Category(name="Foosball", user=user)
skating = Category(name="Skating", user=user)
hockey = Category(name="Hockey", user=user)
db.session.add(soccer)
db.session.add(basketball)
db.session.add(baseball)
db.session.add(frisbee)
db.session.add(snowboarding)
db.session.add(rock)
db.session.add(foosball)
db.session.add(skating)
db.session.add(hockey)
soccer1 = Item(name="soccer1", description="soccer1", category=soccer)
soccer2 = Item(name="soccer2", description="soccer2", category=soccer)
soccer3 = Item(name="soccer3", description="soccer3", category=soccer)
basketball1 = Item(name="basketball1", description="basketball1", category=basketball)
basketball2 = Item(name="basketball2", description="basketball2", category=basketball)
basketball3 = Item(name="basketball3", description="basketball3", category=basketball)
baseball1 = Item(name="baseball1", description="baseball1", category=baseball)
baseball2 = Item(name="baseball2", description="baseball2", category=baseball)
baseball3 = Item(name="baseball3", description="baseball3", category=baseball)
frisbee1 = Item(name="frisbee1", description="frisbee1", category=frisbee)
frisbee2 = Item(name="frisbee2", description="frisbee2", category=frisbee)
frisbee3 = Item(name="frisbee3", description="frisbee3", category=frisbee)
snowboarding1 = Item(name="snowboarding1", description="snowboarding1", category=snowboarding)
snowboarding2 = Item(name="snowboarding2", description="snowboarding2", category=snowboarding)
snowboarding3 = Item(name="snowboarding3", description="snowboarding3", category=snowboarding)
db.session.add(soccer1)
db.session.add(soccer2)
db.session.add(soccer3)
db.session.add(basketball1)
db.session.add(basketball2)
db.session.add(basketball3)
db.session.add(baseball1)
db.session.add(baseball2)
db.session.add(baseball3)
db.session.add(snowboarding1)
db.session.add(snowboarding2)
db.session.add(snowboarding3)
db.session.commit()
